### ISSUE TITLE
Suffix on image resolution

### ISSUE THREAD

**Issue by Marcus9512** [Marcus9512/dd2430#23]
When resizing the images the suffix is after .png which looks a bit weird. For example B1epyN8rlV -> B1epyN8rlV.png.400x400 .

Shouldn't it be  B1epyN8rlV.400x400.png ?

**Comment by JonasRSV** [comment]
Then you have to rewrite the image_resizer, because the resizer resizes all png images. 

Having it after is a hacky way of making sure that only the original images get resized.


E.g say you have the dataset

images/a.png
images/b.png

then run resizer and get

images/a.png.400x400
images/b.png.400x400
images/a.png
images/b.png

if you run another resize you only want to resize a.png and b.png not the already resized,

e.g running resize again with different dimensions should return

images/a.png.800x800
images/b.png.800x800
images/a.png.400x400
images/b.png.400x400
images/a.png
images/b.png

If all images have png as suffix then we need to update so that the resizer knows which images to resize, so that it doesnt also resize the 400x400 images to 800x800.
